version: '3.8'

services:
  frontend:
    build: ./FE
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build: ./BE
    ports:
      - "3001:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
